import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import React from "react";
import NavLinks from "./ui/NavLinks";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>WebToolbox</title>
        <link rel="icon" href="/icon.webp" />
      </head>
      <body className="mx-auto flex flex-col min-h-screen bg-customBg px-4 py-4 text-white">
        <header className="bg-customBg w-full mb-4">
          <div className="container mx-auto px-4 py-3 bg-contentBg rounded-lg">
            <div className="flex">
              <div className="flex-grow flex flex-col">
                <h1 className="text-xl font-bold">
                  {/* Inline icon.webp */}
                  <img src="/icon.webp" className="w-8 inline mr-5" alt="WebToolbox icon" />
                  Devtools inc</h1>
              </div>
            </div>
          </div>
        </header>
        <div className="container mx-auto flex-grow min-w-[320px]">
          <div className="w-full flex flex-col sm:flex-row flex-grow overflow-hidden">
            <aside className="flex-shrink-0 sm:pr-4 sm:min-w-[210px]">
              <NavLinks />
            </aside>
            <main role="main" className="h-full w-full flex-grow px-6 py-4 overflow-auto rounded-lg bg-contentBg">
              {children}
            </main>
          </div>
        </div>
        <footer className="bg-customBg mt-auto w-full pt-4">
          <div className="container mx-auto px-4 py-3 bg-contentBg rounded-lg">
            <div className="flex">
              <div className="flex-grow flex flex-col">
                <a href="https://github.com/LauJosefsen" className="text-xs uppercase tracking-wider">Github</a>
                <a href="https://www.linkedin.com/in/lau-josefsen/" className="text-xs uppercase tracking-wider">LinkedIn</a>
              </div>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}